### ISSUE TITLE
`==` defined by @auto_hash_equals calls `isequal` instead of `==`

### ISSUE THREAD

**Issue by matthias314** [JuliaServices/AutoHashEqualsCached.jl#35]
Wouldn't it be more consistent if `==` applied `==` to all fields? There could be a separate definition for `isequal` that applies `isequal` to all fields.

**Comment by ORBAT** [comment]
I'd see defaulting to `isequal` as a good choice since it'll give you correct results even for the cases where `==` gives silly results, and I'm under the impression that it's what you should be using for equality comparisons of fields anyhow.  That it's inconsistent is in my opinion a bit inconsequential: I'd rather take a `==` that returns sensible results by default rather than having one that uses `==` for comparisons, and then having to have a separate `isequal` method that I'll have to remember to use for my types because `==` can't be trusted.

**Comment by gafter** [comment]
Since this repo has been ported to https://github.com/JuliaServices/AutoHashEquals.jl, this is a dup of https://github.com/JuliaServices/AutoHashEquals.jl/issues/18

**Comment by gafter** [comment]
@ORBAT You're welcome to comment on https://github.com/JuliaServices/AutoHashEquals.jl/issues/18 if you're interested in this topic.  All of this code has moved to https://github.com/JuliaServices/AutoHashEquals.jl (it will become version 1.0 soon) and this repo will be archived.
